### ISSUE TITLE
Bad img URL

### ISSUE THREAD

**Issue by magl88** [poststatus/wptest#60]
Hi 
You have many bad img url 
https://github.com/poststatus/wptest/blob/master/wptest.xml
For example 
http://wptest.io/demo/wp-content/uploads/2011/01/canola2.jpg
http://wptest.io/demo/wp-content/uploads/2011/01/dsc20050315_145007_132.jpg

**Comment by tnorthcutt** [comment]
Fixed in https://github.com/poststatus/wptest/commit/380120511e2157872a82c1c55d3e7a5f584ec580
